services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://admission_bot:strong_password_here@postgres:5432/admission_bot_db
      QDRANT_URL: http://qdrant:6333
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["sh", "-c", "python -m scripts.init_db && python -m app.main"]

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["tools"]
    working_dir: /app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://admission_bot:strong_password_here@postgres:5432/admission_bot_db
      QDRANT_URL: http://qdrant:6333
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["python", "-m", "scripts.load_documents"]

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: admission_bot_db
      POSTGRES_USER: admission_bot
      POSTGRES_PASSWORD: strong_password_here
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admission_bot -d admission_bot_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.15.4
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
  huggingface_cache:
